-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-25 14:38:18 WITA
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Dosen 
    ( 
     NIP        VARCHAR2 (20)  NOT NULL , 
     Nama_Dosen VARCHAR2 (50)  NOT NULL , 
     Email      VARCHAR2 (50) 
    ) 
;

ALTER TABLE Dosen 
    ADD CONSTRAINT Dosen_PK PRIMARY KEY ( NIP ) ;

CREATE TABLE Kelas 
    ( 
     Kode_Kelas          VARCHAR2 (10)  NOT NULL , 
     Tahun_Ajaran        VARCHAR2 (20)  NOT NULL , 
     Hari                VARCHAR2 (20)  NOT NULL , 
     Waktu               DATE  NOT NULL , 
     Ruang               VARCHAR2 (50)  NOT NULL , 
     Dosen_NIP           VARCHAR2 (20)  NOT NULL , 
     Mata_Kuliah_Kode_MK VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE Kelas 
    ADD CONSTRAINT Kelas_PK PRIMARY KEY ( Kode_Kelas ) ;

CREATE TABLE Mahasiswa 
    ( 
     NIM              VARCHAR2 (10)  NOT NULL , 
     Nama_Mhs         VARCHAR2 (100)  NOT NULL , 
     Tahun_Masuk      INTEGER  NOT NULL , 
     Email            VARCHAR2 (50) , 
     Prodi_Kode_Prodi VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE Mahasiswa 
    ADD CONSTRAINT Mahasiswa_PK PRIMARY KEY ( NIM ) ;

CREATE TABLE Mata_Kuliah 
    ( 
     Kode_MK VARCHAR2 (10)  NOT NULL , 
     Nama_MK VARCHAR2 (50)  NOT NULL , 
     SKS     SMALLINT  NOT NULL 
    ) 
;

ALTER TABLE Mata_Kuliah 
    ADD CONSTRAINT Mata_Kuliah_PK PRIMARY KEY ( Kode_MK ) ;

CREATE TABLE Prodi 
    ( 
     Kode_Prodi VARCHAR2 (10)  NOT NULL , 
     Nama_Prodi VARCHAR2 (100)  NOT NULL , 
     Fakultas   VARCHAR2 (100)  NOT NULL 
    ) 
;

ALTER TABLE Prodi 
    ADD CONSTRAINT Prodi_PK PRIMARY KEY ( Kode_Prodi ) ;

CREATE TABLE Regis_MK 
    ( 
     ID_Regis         INTEGER  NOT NULL , 
     Nilai            NUMBER (10,2) , 
     Kelas_Kode_Kelas VARCHAR2 (10)  NOT NULL , 
     Mahasiswa_NIM    VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE Regis_MK 
    ADD CONSTRAINT Regis_MK_PK PRIMARY KEY ( ID_Regis ) ;

ALTER TABLE Kelas 
    ADD CONSTRAINT Kelas_Dosen_FK FOREIGN KEY 
    ( 
     Dosen_NIP
    ) 
    REFERENCES Dosen 
    ( 
     NIP
    ) 
;

ALTER TABLE Kelas 
    ADD CONSTRAINT Kelas_Mata_Kuliah_FK FOREIGN KEY 
    ( 
     Mata_Kuliah_Kode_MK
    ) 
    REFERENCES Mata_Kuliah 
    ( 
     Kode_MK
    ) 
;

ALTER TABLE Mahasiswa 
    ADD CONSTRAINT Mahasiswa_Prodi_FK FOREIGN KEY 
    ( 
     Prodi_Kode_Prodi
    ) 
    REFERENCES Prodi 
    ( 
     Kode_Prodi
    ) 
;

ALTER TABLE Regis_MK 
    ADD CONSTRAINT Regis_MK_Kelas_FK FOREIGN KEY 
    ( 
     Kelas_Kode_Kelas
    ) 
    REFERENCES Kelas 
    ( 
     Kode_Kelas
    ) 
;

ALTER TABLE Regis_MK 
    ADD CONSTRAINT Regis_MK_Mahasiswa_FK FOREIGN KEY 
    ( 
     Mahasiswa_NIM
    ) 
    REFERENCES Mahasiswa 
    ( 
     NIM
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
